var agenda = {
  nodes: [
    { id: "C#", priority: 1, parent: null },
    { id: "javaScript", priority: 1, parent: null },
    { id: "Data Types", priority: 1, passed: false, parent: "C#" },
    { id: "Value Types", priority: 1, passed: true, parent: "Data Types" },
    { id: "Integers", priority: 1, passed: true, parent: "Value Types" },
    { id: "ّFloating_points", priority: 1, passed: true, parent: "Value Types" },
    { id: "Enumeration", priority: 1, passed: true, parent: "Value Types" },
    { id: "Tuple", priority: 1, passed: true, parent: "Value Types" },
    { id: "Char", priority: 1, passed: true, parent: "Value Types" },
    { id: "DateTime", priority: 1, passed: true, parent: "Value Types" },
    { id: "Refrence Types", priority:1, passed: false, parent: "Data Types" },
    { id: "String", priority: 1, passed: false, parent: "Refrence Types" },
    { id: "Json", priority: 1, passed: true, parent: "javaScript" },
  ],
  links: [
    { source: "Data Types", target: "C#"},
    { source: "Value Types", target: "Data Types" },
    { source: "Integers", target: "Value Types" },
    { source: "ّFloating_points", target: "Value Types" },
    { source: "Enumeration", target: "Value Types"},
    { source: "Tuple", target: "Value Types"},
    { source: "Char", target: "Value Types"},
    { source: "DateTime", target: "Value Types"},
    { source: "Refrence Types", target: "Data Types"},
    { source: "String", target: "Refrence Types" },
    { source: "Json", target: "javaScript" },
  ],
};
